---
name: Check Commit Message

on:
  workflow_call:


jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(#\d{3,6}|((dbeaver|cloudbeaver).+?#\d{3,6})|((DB-|CB-|DVO-)\d+))\s.*$'
          error: |
            Each commit message must begin with GitHub or Jira ticket reference. Like:
            *  #<issue_nember>
            *  repo#<issue_nember>
            *  org/repo#<issue_nember>
            *  DB-Number (Jira)
            *  CB-Number (Jira)

            For how to rename your commit message follow this GitHub Doc:
            https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message